# Network Crawler Configuration

# Threading Configuration
threading:
  max_workers: 4
  queue_timeout: 30  # seconds

# Database Configuration
database:
  path: "network_inventory.db"
  journal_mode: "WAL"  # Write-Ahead Logging for better concurrency

# Connection Settings
connection:
  timeout: 30  # seconds
  retry_attempts: 3
  retry_delay: 5  # seconds

# Logging Configuration
logging:
  level: "INFO"
  file: "crawler.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# Output Configuration
output:
  directory: "outputs"
  inventory_file: "final_inventory.csv"

# Device Filtering
filtering:
  exclude_platforms:
    - "AIR-"
    - "CP-"
    - "Cisco IP Phone"
    - "SPA-"
    - "ATA-"
  include_platforms:
    - "switch"
    - "router"
    - "firewall"
    - "nexus"
    - "nx-os"
    - "ios-xe"
    - "ios xe"
    - "ios" 